[build]
  # This points to the directory where your functions are located
  functions = "netlify/functions"
  # Optionally, specify the publish directory if you're building a static site

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"

[[redirects]]
  # Redirect requests to /api/birthchart to the serverless function
  from = "/api/birthchart"
  to = "/.netlify/functions/birthchart"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]

[[redirects]]
  # Redirect requests to /api/navamshachart to the serverless function
  from = "/api/navamshachart"
  to = "/.netlify/functions/navamshachart"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]

